### PR TITLE
ADD: sample from latest version of Rainbow (Leonardo)

### PR DESCRIPTION
**Pull request by egouden**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@egouden Thanks for adding this. You would need to update the registry as written here https://github.com/openradar/open-radar-data#adding-new-datasets. Please also mention the new data in the `README.md`.

Are there any changes in the format which need to be tackled here?

**Comment by egouden** [comment]
The PR has been updated. I see unexpected changes related to other data files.

There are some changes between the Rainbow 5.36 version (2013051000000600dBZ.vol) and the last version (5.59). I wanted to share this information. I am not sure what should be considered as a change in format and what should be the guidelines for sharing such changes in this project. This is an open question related to this pull request.

**Comment by kmuehlbauer** [comment]
Thanks Edouard, I'll have a look at the failing CI runs. Otherwise this PR looks fine so far.

**Comment by kmuehlbauer** [comment]
Let's try the new file over at [xradar](https://github.com/openradar/xradar). Thanks for adding, @egouden.

**Pull request merged**
